services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persistedcachedb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  
volumes:
  mysql: