services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persistedcachedb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: persistedcachedb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Secret123!"
      DATABASE_NAME: persistedcachedb
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
  
volumes:
  mysql:
  postgres:
  sqlserver: