services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persistedcachedb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: persistedcachedb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
volumes:
  mysql:
  postgres: