<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>false</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" Version="4.18.1" />
        <PackageReference Include="coverlet.collector" Version="8.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="[7.2.1]" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="Testcontainers.MongoDb" Version="4.1.0" />
        <PackageReference Include="Testcontainers.MsSql" Version="4.1.0" />
        <PackageReference Include="Testcontainers.MySql" Version="4.1.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.1.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\PersistedCache.FileSystem\PersistedCache.FileSystem.csproj" />
      <ProjectReference Include="..\..\src\PersistedCache.MongoDb\PersistedCache.MongoDb.csproj" />
      <ProjectReference Include="..\..\src\PersistedCache.MySql\PersistedCache.MySql.csproj" />
      <ProjectReference Include="..\..\src\PersistedCache.PostgreSql\PersistedCache.PostgreSql.csproj" />
      <ProjectReference Include="..\..\src\PersistedCache.Sqlite\PersistedCache.Sqlite.csproj" />
      <ProjectReference Include="..\..\src\PersistedCache.SqlServer\PersistedCache.SqlServer.csproj" />
    </ItemGroup>

</Project>
