<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RootNamespace>PersistedCache</RootNamespace>
        <WarningsNotAsErrors>NU1901,NU1902,NU1903,NU1904</WarningsNotAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Mikkel Buhl</Authors>
        <Description>Simple persisted cache for .NET and Microsoft Sql Server</Description>
        <PackageId>PersistedCache.SqlServer</PackageId>
        <PackageTags>cache storage database sql sqlserver mssql</PackageTags>
        <PackageProjectUrl>https://github.com/mnbuhl/PersistedCache</PackageProjectUrl>
        <RepositoryUrl>https://github.com/mnbuhl/PersistedCache</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Copyright>Copyright © 2024 Mikkel Buhl</Copyright>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PersistedCache\PersistedCache.csproj" />
    </ItemGroup>
</Project>
