name: Build and test

on:
  push:
      branches: [ main ]
      paths: [ 'src/**', 'tests/**', '.github/workflows/**' ]
  pull_request:
      branches: [ main ]
      paths: [ 'src/**', 'tests/**', '.github/workflows/**' ]

  workflow_call:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0' ]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Setup Sqlite for testing
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
