name: Publish all PersistedCache packages to NuGet
on:
  workflow_dispatch:

jobs:
  publish-package:
    name: Publish all PersistedCache packages to NuGet
    uses: ./.github/workflows/publish-reuse.yml
    with:
      PACKAGE_ID: "['PersistedCache', 'PersistedCache.SqlServer', 'PersistedCache.MySql', 'PersistedCache.PostgreSql', 'PersistedCache.Sqlite', 'PersistedCache.FileSystem', 'PersistedCache.MongoDb']"
    secrets: inherit
